Review task1
hgutierrezg/shared-timesheet pull request #1
Opened 2022-01-31 22:00 UTC by hgutierrezg

2022-02-01 16:46 UTC, chriswbluer commented on src/main/java/com/hgutierrezg/training/repository/TimesheetRepository.java
> +    /**
nice comments

2022-02-01 17:32 UTC, Mbd06b requested changes
The only requirement I see missing is demonstrating the Synchronous form submit, with a required and optional field.  I reccomend adding a simple userRegistration.jsp that you can bind a form to and display a a property with that form submit with `${  }`  reference in a header element of your timesheet dashboard.

2022-02-01 17:32 UTC, Mbd06b commented on pom.xml
> +		</dependency>
spring-context is duplicated here,  check your dependency hierarchy. spring-webmvc contains spring-context

2022-02-01 17:32 UTC, Mbd06b commented on src/main/java/com/hgutierrezg/training/controller/IndexController.java
> +            return "timesheet";
you might want to rename the reference to the page "timesheet" to "timesheetPage", to avoid confusion with a rest endpoint that might "Represent" the timesheet object.

2022-02-01 17:32 UTC, Mbd06b commented on src/main/java/com/hgutierrezg/training/model/Timesheet.java
> +public class Timesheet {
Refactor this to TimesheetView, later when you need a model for Hibernate, cerate a TimesheetImpl,  both these classes can inherit from an Timesheet interface.

2022-02-01 17:32 UTC, Mbd06b commented on src/main/java/com/hgutierrezg/training/model/Timesheet.java
> +    }
avoid overriding equals unless you have a functional need to do so.

2022-02-01 17:32 UTC, Mbd06b commented on src/main/java/com/hgutierrezg/training/service/TimesheetService.java
> +    private final TimesheetRepository timesheetRepository;
You have a TimesheetRepository bean annotated as an @Repository, you should be able to Autowire this in the Service.

2022-02-01 17:32 UTC, Mbd06b commented on src/main/java/filters/CorsFilter.java
> + public class CorsFilter implements Filter {
this shouldn't be necessary for locally hosted js communicating with the same server.

2022-02-01 17:32 UTC, Mbd06b commented on src/main/webapp/components/dashboard/dashboard.html
> +                <li ng-click="dashboardController.menuSelection('employee') "
508 Accessibility Compliance.  All interactive components need a unique ID. 
https://www.deque.com/blog/unique-id-attributes-matter/

2022-02-01 17:32 UTC, Mbd06b commented on src/main/webapp/components/dashboard/dashboard.html
> +        <div class="col-sm-3 sidenav">
508 Accessibility Compliance. use a `<nav>` semantic html5 element to describe your navigation. https://www.w3schools.com/html/html5_semantic_elements.asp

2022-02-01 17:32 UTC, Mbd06b commented on src/main/webapp/components/dashboard/dashboard.html
> +                    ng-class="{ 'active' : dashboardController.role == 'internalManager' }"><a href="#internalManager">Internal
508  Accessibility compliance.  ng-click and an 'a' tag. This is a case of "nested interactive elements" which will cause issues. 
https://accessibilityinsights.io/info-examples/web/nested-interactive/

2022-02-01 17:32 UTC, Mbd06b commented on src/main/webapp/components/timesheet-form/timesheet-form.component.js
> + * Creating controller only inside sharedTimesheetApp module,
Just note at a high level, while components are good to understand, particularly for UI pattern development. I would be sure to study the Module -> Controller -> Service  components of AngularJS to get a clear familiarity with the application architecture you might encounter.

2022-02-01 17:32 UTC, Mbd06b commented on src/main/webapp/components/timesheet-list/timesheet-list.html
> +                        class="btn btn-success custom-width">Approve
id attribute

2022-02-01 17:32 UTC, Mbd06b commented on src/main/webapp/service/timesheet.service.js
> +function timesheetService($http, $q) {
consider refactoring this service using promise syntax, you can completely avoid using $q defer library dependency.

2022-02-02 14:00 UTC, hgutierrezg commented on src/main/java/com/hgutierrezg/training/controller/IndexController.java
> +            return "timesheet";
This page is removed now, was not needed since index.html is the one being served

2022-02-02 14:01 UTC, hgutierrezg commented on src/main/java/com/hgutierrezg/training/model/Timesheet.java
> +public class Timesheet {
This was changed by creating Dto and Model object and mapping them with Mapstruct

2022-02-02 14:05 UTC, hgutierrezg commented on src/main/java/com/hgutierrezg/training/service/TimesheetService.java
> +    private final TimesheetRepository timesheetRepository;
Here is spring doing the injection too, not with the Autowire annotation but with the constructor injection. 
The constructor is generated by lombok with @AllArgsConstructor.

2022-02-04 16:59 UTC, merged